build:
    environment:
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false

    tests:
        stop_on_failure: true
        override:
            -
                command: vendor/bin/parallel-lint src/ tests/ scripts/
            -
                command: vendor/bin/phpcs -sp src/ tests/ scripts/
            -
                command: vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
            -
                command: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'

    nodes:
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1

filter:
    excluded_paths: ['tests/*', 'vendor/*']

checks:
    php:
        code_rating: true
        duplication: true
